### ISSUE TITLE
CModule Logs

### ISSUE THREAD

**Issue by anfelbeghoura** [Azure/azure-iot-edge-c-module#2]
Hello 
I have question please: I want to visualize the CModule's logs to see what is happening.  I can't find a way to see the messages sent from the downstream device are actually received by the gateway neither in visual studio code nor  using  ""iotedge logs CModule"" command 
Thank you

**Comment by blackchoey** [comment]
@anfelbeghoura can you raise your request at https://github.com/azure/iotedge? If you routes the message to one module, you can print some logs when the module receives the message. Otherwise some support from runtime is required for your scenario.

**Comment by konichi3** [comment]
@marianan pls closed this
