### ISSUE TITLE
Is the use of ubuntu as base image problematic with regards to ubuntus intellectual property rights policy?

### ISSUE THREAD

**Issue by alaendle** [Azure/azure-iot-edge-c-module#7]
https://github.com/Azure/azure-iot-edge-c-module/blob/10759c749335db543338e15e5bb4f1a2661f8276/Dockerfile.amd64#L1

As far as I understand https://ubuntu.com/legal/intellectual-property-policy (especially "You can modify Ubuntu for personal or internal commercial use.") you are not allowed to redistribute modules commercially. That leads to uncertainty in many cases, e.g. what about the simple and free handover to another member of a corporate group (is this still an "internal commercial use" or not?).

Since a provided template will often be used as the base of real world applications, the choice of ubuntu as a base image might lead to legal/compliance problems that might be spotted relative late during the projects. 

So is there a reason why especially ubuntu was chosen? Or would another distribution like alpine or debian would make more sense and avoid legal problems? And would it make sense to adopt the template?

(I'm not a lawyer, so I'm not sure how problematic the IP rights policy is, my point is more that one should avoid this problem in the first place)

**Comment by konichi3** [comment]
Thank you @alaendle for asking the question. We will follow up internally and respond back on this.

Reading the [IP site](https://ubuntu.com/legal/intellectual-property-policy), it looks like redistribution rights are granted as long as the modifications are not made. 

>>You can redistribute Ubuntu, but only where there has been no modification to it.
>>You can redistribute Ubuntu in its unmodified form, complete with the installer images and packages provided by Canonical (this includes the publication or launch of virtual machine images).

**Comment by konichi3** [comment]
Closing the issue. Let us know if you have any further questions.

**Comment by alaendle** [comment]
@konichi3 - That's not the kind of response I was hoping for, because it is still unclear, if a commercial redistribution of an edge module based on Ubuntu seems to be allowed. 

I think at least some would claim, that the additional layers that we add to the Ubuntu image are a kind of modification of the image and therefore prohibit commercial redistribution. My feeling is also that there must be a reason why nearly every commercial image you find on hub.docker.com is based on alpine or debian.

Since Microsoft intentionally choose Ubuntu as a base image for customer projects, my interpretation is that Microsoft sees no contradiction between the Ubuntu IP and commercial redistribution?

**Comment by konichi3** [comment]
Hi @alaendle 

Thanks for your additional comments. You raise legal questions that should be answered by your legal counsel, as we are unable to opine on the interpretation of Ubuntu’s policy terms. 

Please note that our template is available under a [license](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-iot-edge-c-module%2Fblob%2Fmaster%2FLICENSE&data=04%7C01%7Ckoichih%40microsoft.com%7C756ede87bbbd4b04410808d9eb6589f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637799643607370819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e5Q7NEKWWFtXVRhbcO9xJ8d4dZJE%2F1z%2B9Ie1xajiTXU%3D&reserved=0), and your legal counsel can also answer any questions you may have on our license terms and your use of our template.
